name: LangBoltz_env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fqdn=1.5.1
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.36.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus_client=0.22.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - send2trash=1.8.3
  - setuptools=80.8.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zstandard=0.23.0
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.4
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - biopython==1.85
      - biotite==1.2.0
      - biotraj==1.2.2
      - cftime==1.6.4.post1
      - cloudpathlib==0.21.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - einops==0.8.1
      - esm==3.2.0
      - filelock==3.18.0
      - fire==0.7.1
      - fonttools==4.61.0
      - frozenlist==1.6.0
      - fsspec==2025.5.1
      - h5py==3.15.1
      - hf-xet==1.1.2
      - huggingface-hub==0.32.2
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - lightning-utilities==0.14.3
      - matplotlib==3.10.7
      - mdtraj==1.10.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - multidict==6.4.4
      - netcdf4==1.7.2
      - networkx==3.4.2
      - nglview==3.1.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pandas==2.2.3
      - peft==0.15.2
      - pillow==11.2.1
      - propcache==0.3.1
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.1.post0
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sympy==1.14.0
      - tenacity==9.1.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - torchmetrics==1.7.2
      - torchtext==0.18.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.48.1
      - triton==3.3.0
      - tzdata==2025.2
      - yarl==1.20.0
      - zstd==1.5.7.0
